# Generated by Django 4.2 on 2023-05-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='title',
            new_name='description',
        ),
    ]
