# Generated by Django 4.2 on 2023-06-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_read_message_pk',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
