# Generated by Django 4.2 on 2023-08-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membership_last_read_message_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='last_read_message_pk',
            field=models.BigIntegerField(default=0),
        ),
    ]
